version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    networks:
      - enrollment
    environment:
      - TOKEN=6101250366:AAFd8UZBbg2pTv8ic1KTRTMo77vRdluQFyg

  db:
    container_name: db
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - enrollment

networks:
  enrollment:
    driver: bridge
