version: "3.9"

services:
  app:
    container_name: app
    build:
      context: .
    depends_on:
      - db
    links:
      - db
    environment:
      TOKEN: 6101250366:AAFd8UZBbg2pTv8ic1KTRTMo77vRdluQFyg
      HOST: db
      PORT: 5432
      USER: postgres
      POSTGRES_PASSWORD: password
      DBNAME: postgres
      SSLMODE: disable

  db:
    container_name: db
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_PASSWORD:password

